# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e3eced96c9e9c53c4786f3d552544ecc3579c3544dd24a18309cd7cebe087630677b65e10dd6ad9741b4c36c5a241940e353c2139d811960e9262c1b155cab8
  gmail_username: 'ryanimmesberger@gmail.com'
  gmail_password: ''
  api_key: 'key-b98f3e569dc2675cc8406086a6b461b3'
  domain: 'smtp.mailgun.org'
  username: 'e18861b0857c5390773296985b88851b'
  password: 'e18861b0857c5390773296985b88851b'

test:
  secret_key_base: 16d73612b60e447b96682215ceaf3ef63946d593bddc6f8fc88de389126b13f7c47a7f2fa9ee605f775487d6fd942e64d45ec8f22707fcd4ef44ac4d01c4b816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
